dist: bionic
language: node_js
node_js:
  - 12.16.1
cache: yarn
git:
  depth: false
branches:
  only:
    - develop
    - "/^hotfix\\/.*$/"
    - "/^release\\/.*$/"
env:
  - TEST_SUITE="./build.sh sonar"
  - TEST_SUITE="./ci-scripts/e2e-cypress.sh"
script: $TEST_SUITE
deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/publish-builds.sh
  on:
    branch: develop
notifications:
  email:
    on_failure: always
    on_success: change
addons:
  chrome: stable
  sonarcloud:
    organization: sap
